services:
  eres_sylius_iyzico_plugin.controller.payum:
    class: Eres\SyliusIyzicoPlugin\Controller\PayumController
    public: true
    arguments:
      - "@payum"
      - "@sylius.repository.order"
      - "@=service('sylius.resource_registry').get('sylius.order')"
      - "@sylius.resource_controller.request_configuration_factory"
      - "@sylius.resource_controller.view_handler"
      - "@router"
      - "@sylius.factory.payum_get_status_action"
      - "@sylius.factory.payum_resolve_next_route"
